### ISSUE TITLE
alternateClassName are ignored

### ISSUE THREAD

**Issue by simonmilz** [junghans-schneider/gulp-extjs#2]
```js
Ext.define('Ext.plugin.Abstract', {
    alternateClassName: 'Ext.AbstractPlugin',
```

![image](https://cloud.githubusercontent.com/assets/5016123/22788224/61b4dce2-eedf-11e6-96dc-970f9b507fdd.png)

**Comment by til-schneider** [comment]
gulp-extjs doesn't scan your whole code base. Instead it resolves your dependencies as it reads your project starting from the entry points. This way only the involved code files are read which is a lot faster.

As a result, gulp-extjs is not able to know about aliases if they are not defined elsewhere. So if you have such an alias in your code base, please add it to your configuration.

Example:

    .pipe(extjs({
        ...
        resolve: {
            alias: {
                'Ext.AbstractPlugin': 'Ext.plugin.Abstract'
            }
        }
    })

**Comment by simonmilz** [comment]
@til-schneider thx for this info!
